### ISSUE TITLE
discord.callback() returns insecure transport error over HTTPS

### ISSUE THREAD

**Issue by damoncasale** [weibeu/Flask-Discord#3]
Started getting this error two days ago:

(insecure_transport) OAuth 2 MUST utilize https.

My redirect url is https://(fooblah domain)/api/login

What gives?

I'm using Python proxied to http://localhost:9999 in Nginx, but that shouldn't affect anything, should it?

**Comment by damoncasale** [comment]
I'm now certain that this library is the problem.  I just substituted discord.callback() and discord.fetch_user() with manual calls, and they work just fine.  I double-checked that I'm getting the code query string param.

Please fix.

**Comment by thec0sm0s** [comment]
Normally, you shouldn't be getting that error. From the documentation of [requests_oauthlib](https://requests-oauthlib.readthedocs.io/en/latest/examples/real_world_example.html):

> N.B: You should note that Oauth2 works through SSL layer. If your server is not parametrized to allow HTTPS, the fetch_token method will raise an oauthlib.oauth2.rfc6749.errors.InsecureTransportError. Most people don’t set SSL on their server while testing and that is fine. You can disable this check in two ways:

By setting an environment variable.
`export OAUTHLIB_INSECURE_TRANSPORT=1`
2. Equivalent to above you can set this in Python (if you have problems setting environment variables)

```
# Somewhere in webapp_example.py, before the app.run for example
import os
os.environ['OAUTHLIB_INSECURE_TRANSPORT'] = '1'
```

If that doesn't works for you, make sure that you're not overriding the flask configs with keys that are already being used by the library stored in this [config file](https://github.com/thec0sm0s/Flask-Discord/blob/master/flask_discord/configs.py).

**Comment by thec0sm0s** [comment]
This thread has been inactive for months so I will assume your issues has been fixed already and will close this.

**Comment by damoncasale** [comment]
SSL *is* set on my server.  This is still an issue.

**Comment by thec0sm0s** [comment]
Are you sure you have set `os.environ['OAUTHLIB_INSECURE_TRANSPORT'] = '1'` before your `app.run(...)`? I think you need this since your flask app is served as Nginx proxy?

**Comment by thec0sm0s** [comment]
Just a heads up to this.

### Why I should use SSL?
OAuth2 basically lets your application access protected resources of the user. To make this happen, your application is granted an OAuth2 Token specific to this user which is then used to get the all of the resources which are available within the scope of this token.
Remember this is the same token which will give access to all of the protected resources and is similar to the user's password, except it allows only some particular protected resources. Users authorize your application so that you can go ahead and make a request to the server to get this token. When granted, this token is transported to your application via HTTP and if you're not using HTTPS, it will be transported in clear plain text. And you already know we shouldn't deal with plain texts passwords. Its the same.

## What is the issue?
Most common way to deploy Flask applications is setting them up behind some reverse proxy servers like Nginx. The problem with this is when the user is redirected back to your callback URL (which is HTTPS), it's first handled by your reverse proxy servers which then forwards it to instance of your Flask application. For the application, this request seems coming from your reverse proxy server, not the user. Which in many cases makes the `https://...` to `http://` making your Flask application think the transport is being done over HTTP.

## How to properly setup Flask application behind reverse proxy servers?
So yeah, now you know why this issue appears at first place. But we are lucky that Werkzeug already provides a middleware interface, [X-Forwarded-For Proxy Fix](https://werkzeug.palletsprojects.com/en/1.0.x/middleware/proxy_fix/#x-forwarded-for-proxy-fix) to handle this situation effectively.

To make use of this middleware, simply bind instance of your Flask application with the Werkzeug `ProxyFix`.
```python
from werkzeug.middleware.proxy_fix import ProxyFix
# App is behind one proxy that sets the -For and -Host headers.
app = ProxyFix(app, x_for=1, x_host=1)
```

**Comment by relyt29** [comment]
> So yeah, now you know why this issue appears at first place. But we are lucky that Werkzeug already provides a middleware interface, [X-Forwarded-For Proxy Fix](https://werkzeug.palletsprojects.com/en/1.0.x/middleware/proxy_fix/#x-forwarded-for-proxy-fix) to handle this situation effectively.
> 
> To make use of this middleware, simply bind instance of your Flask application with the Werkzeug `ProxyFix`.
> 
> ```python
> from werkzeug.middleware.proxy_fix import ProxyFix
> # App is behind one proxy that sets the -For and -Host headers.
> app = ProxyFix(app, x_for=1, x_host=1)
> ```


The fix supplied here does not appear to work for me, the [documentation](https://werkzeug.palletsprojects.com/en/2.0.x/middleware/proxy_fix/) itself for Werkzeug says clearly that the return type of the ProxyFix function is `None`. 

So it doesn't really make sense to do something like app=ProxyFix(blah) because that sets app to None. 

I am unsure how to make it work if you overload any parameters at all in the default flask object, e.g. if you use things like `@app.before_first_request` or you overwrite anything in `app.config` - I assume it must be possible but I haven't figured it out

**Comment by weibeu** [comment]
`ProxyFix(...)` just returns its own instance. Thanks for pointing it out. I think werkzeug expects a wsgi application. It doesn't knows what Flask application is. From here: [`Flask.wsgi_app`](https://flask.palletsprojects.com/en/2.0.x/api/#flask.Flask.wsgi_app), try the following and see how it goes.
```
from werkzeug.middleware.proxy_fix import ProxyFix
# App is behind one proxy that sets the -For and -Host headers.
app.wsgi_app = ProxyFix(app.wsgi_app, x_for=1, x_host=1)

```

As they mentioned, this way we can apply middlewares while still having reference to our original flask application. Try it how it goes for you and then I will update the previous answer if it appears working.
Again thanks for mentioning this, I had just quoted the example from werkzeug docs 😅.
