### ISSUE TITLE
Error on request with parameter

### ISSUE THREAD

**Issue by m0ssa99** [weibeu/Flask-Discord#39]
i try to get a guild member, without limit parameter i get only 1 member
`discord.bot_request("/guilds/{GUILDID}/members",data=dict(limit=100))`
i get error **simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)**

**Comment by weibeu** [comment]
API v9 docs states that `limit` and other arguments should be passed as query parameter. I tried this which worked for me.
```python
discord.bot_request("/guilds/690878977920729177/members", params=dict(limit=100))
``` 
Anyways about getting JSONDecodeError, as I can see its coming from `simplejson.errors.JSONDecodeError` and Flask-Discord is set to use and handle exceptions of the json from the Python standard library. So I would advise to uninstall simplejson so that it uses the default json library.

If issue still persists then let me know I would fix this in upcoming updates.

**Comment by weibeu** [comment]
I will close this issue for now. Feel free to re-open if you get any further troubles implementing the same.
